### ISSUE TITLE
Calendar scheduler error

### ISSUE THREAD

**Issue by LeonLiuY** [rhinobird-io/rhinobird-web#167]
Calendar not sending reminders before 30 min now.

This is the log

```
2015-07-15T06:32:56UTC platform[web.1]: { 70228313025080 rufus-scheduler intercepted an error:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080   job:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     Rufus::Scheduler::EveryJob "30s" {}
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080   error:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     70228313025080
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     ActiveRecord::StatementInvalid
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT "events".* FROM "events" WHERE (repeated = 't' and status <> 1)
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `call'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `loop'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080   tz:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     ENV['TZ']: 
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     Time.now: 2015-07-15 06:32:56 +0000
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080   scheduler:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     opts:
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       {}
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       frequency: 0.3
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       scheduler_lock: #<Rufus::Scheduler::NullLock:0x007fbe9b36b530>
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       trigger_lock: #<Rufus::Scheduler::NullLock:0x007fbe9b36b508>
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     uptime: 1297206.042566579 (2w1d20m6s42)
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     down?: false
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     threads: 2
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       thread: #<Thread:0x007fbe9b36b4b8>
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       thread_key: rufus_scheduler_70228312284160
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080         vacant: 0
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080         max_work_threads: 28
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       mutexes: {}
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     jobs: 1
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       at_jobs: 0
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       in_jobs: 0
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       every_jobs: 1
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       interval_jobs: 0
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080       cron_jobs: 0
2015-07-15T06:32:56UTC platform[web.1]:   70228313025080     work_queue: 0
2015-07-15T06:32:56UTC platform[web.1]: } 70228313025080 .
```

**Comment by LeonLiuY** [comment]
Fixed
